### ISSUE TITLE
Software versions

### ISSUE THREAD

**Issue by sparrow217** [micahswab/RiskMetrics#21]
Some of the software versions are vague. For instance, I was confused about which virtualenv version I needed to download( I just downloaded the most recent version, which is 15.1.0). However I had installation issues when I used the recent version and I had to download an older version to get the installation running(15.0.0).

**Comment by hacksmath** [comment]
15.1.0 is what I am using. I'll look into what works on Linux.

**Comment by hacksmath** [comment]
Specified version for virtual env in readme.
